@startuml

abstract Usuario {
  + nome: str
  + cpf: str
  + data_nascimento: str
  + email: str
  + senha: str
  + carteira: Carteira
}

class UsuarioPadrao {
  + tipo_conta: str
  + taxa: float
}

class UsuarioDemo {
  + tipo_conta: str
  + taxa: float
}

class Carteira {
  + cpf: str
  + saldo: float 
  + senha_transacao: str
  + lista_de_acoes: List[Acao]
  + historico_de_negociacoes: List[Boleta] 
}

class Corretora {
  + acoes_disponiveis: List[Acao]
  - carregar_acoes_disponiveis(): None
  + fazer_transacao(carteira: Carteira, valor: float): bool 
  + negociar_acao(carteira: Carteira, acao: Acao, quantidade: int): bool
}

class Boleta {
  + cpf: str
  + data: str
  + ticker: str
  + quantidade: int
  + preco_medio: float 
  + taxas: float
  + tipo: str
}

class Acao {
  + ticker: str
  + nome_empresa: str
  + preco_atual: float
  + historico_precos: DataFrame
  + atualizar(): bool
}

class Downloader {
  + download_ticker(ticker: str): DataFrame
  + atualizar_historico(ticker: str): bool
}

class Database {
  + carregar_usuario(cpf: str): Pessoa
  + salvar_usuario(pessoa: Pessoa): bool
  + carregar_acao(ticker: str): Acao
  + salvar_historico(acao: Acao): bool
}

class Aplicativo {
  - usuario_atual: Usuario
  - ultimo_frame: Frame
  - frames: dict[str, Frame]
  + inicializar(): None
  + encerrar(): None
  + exibir_frame(nome: str): None
}

abstract Frame {
  + evento_exibido(): None
}

class TelaLogin {
  + evento_login(): None
  + evento_tela_cadastro(): None
}

class TelaCadastro {
  + evento_cadastro(): None
  + evento_tela_login(): None
}

class TelaDashboard {
  + evento_sair(): None
  + evento_tela_acoes_disponiveis(): None
  + evento_tela_acoes_possuidas(): None
  + evento_tela_historico(): None
}

class TelaAcoesDisponiveis {
  + evento_voltar(): None
  + evento_selecionar_acao(): None
}

class TelaAcoesPossuidas {
  + evento_voltar(): None
  + evento_selecionar_acao(): None
}

class TelaHistorico {
  + evento_voltar(): None
}

class TelaAcao {
  + evento_voltar(): None
  + evento_atualizar(): None
}

Usuario *- Carteira
UsuarioPadrao <|- Usuario 
UsuarioDemo <|- Usuario

Carteira *-- Boleta
Carteira o-- Acao
Corretora o-- Acao
Corretora ..> Carteira
Downloader ..> Acao
Database ..> Pessoa
Database ..> Acao
Aplicativo *-- Frame

Frame <|- TelaLogin
Frame <|- TelaCadastro
Frame <|- TelaDashboard
Frame <|- TelaAcoesDisponiveis
Frame <|- TelaAcoesPossuidas
Frame <|- TelaHistorico

@enduml