@startuml Architecture

abstract Usuario {
  + nome: str
  + cpf: str
  + data_nascimento: str
  + email: str
  + senha: str
  + carteira: Carteira
}

class UsuarioPadrao {
  + tipo_conta: str
  + taxa: float
}

class UsuarioDemo {
  + tipo_conta: str
  + taxa: float
}

class Carteira {
  + cpf: str
  + saldo: float 
  + senha_transacao: str
  + lista_de_acoes: List[Acao]
  + historico_de_negociacoes: List[Boleta] 
}

class Corretora {
  + acoes_disponiveis: List[Acao]
  - carregar_acoes_disponiveis(): None
  + fazer_transacao(carteira: Carteira, valor: float): bool 
  + negociar_acao(carteira: Carteira, acao: Acao, quantidade: int): bool
}

class Boleta {
  + cpf: str
  + data: str
  + ticker: str
  + quantidade: int
  + preco_medio: float 
  + taxas: float
  + tipo: str
}

class Acao {
  + ticker: str
  + nome_empresa: str
  + preco_atual: float
  + historico_precos: DataFrame
  + atualizar(): bool
}

class Downloader {
  + download_ticker(ticker: str): DataFrame
  + atualizar_historico(ticker: str): bool
}

class Database {
  + carregar_usuario(cpf: str): Pessoa
  + salvar_usuario(pessoa: Pessoa): bool
  + carregar_acao(ticker: str): Acao
  + salvar_historico(acao: Acao): bool
}

class Interface {

}

class Frame {
}

Usuario *- Carteira
UsuarioPadrao <|- Usuario 
UsuarioDemo <|- Usuario

Carteira *-- Boleta
Carteira o-- Acao
Corretora o-- Acao
Corretora ..> Carteira
Downloader ..> Acao
Database ..> Pessoa
Database ..> Acao
Frame -|> Interface

@enduml